### ISSUE TITLE
Sublime Text 3 getting a TypeError when running Show Definition

### ISSUE THREAD

**Issue by Rgrable** [acabin/docphp#10]
Since about 2 weeks ago, I've started getting a type error when running `DocPHP: Show Definition` on MacOS. 

```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1066, in run_
    return self.run(edit, **args)
  File "/Users/user/Library/Application Support/Sublime Text 3/Installed Packages/DocPHPManualer.sublime-package/docphp.py", line 331, in run
  File "/Users/user/Library/Application Support/Sublime Text 3/Installed Packages/DocPHPManualer.sublime-package/docphp.py", line 344, in show_popup
  File "/Users/user/Library/Application Support/Sublime Text 3/Installed Packages/DocPHPManualer.sublime-package/docphp.py", line 412, in formatPopup
  File "./python3.3/html/parser.py", line 145, in feed
  File "./python3.3/html/parser.py", line 189, in goahead
  File "./python3.3/html/parser.py", line 372, in parse_starttag
  File "/Users/user/Library/Application Support/Sublime Text 3/Installed Packages/DocPHPManualer.sublime-package/docphp.py", line 528, in handle_startendtag
  File "/Users/user/Library/Application Support/Sublime Text 3/Installed Packages/DocPHPManualer.sublime-package/docphp.py", line 557, in get_tag_text
  File "/Users/user/Library/Application Support/Sublime Text 3/Installed Packages/DocPHPManualer.sublime-package/docphp.py", line 557, in <lambda>
TypeError: can only concatenate tuple (not "str") to tuple
```

**Comment by szabi7** [comment]
Same for me on Sublime Text 3.1.1 Build 3176, OS Linux Mint 17.3

**Comment by vaajnur** [comment]
same error  Build 3176 Debian

**Comment by szabi7** [comment]
Fixed it using the solution from the PR (https://github.com/garveen/docphp/pull/13)

Change docphp.py file from this path as in the PR  
/home/{USER}/.config/sublime-text-3/Installed Packages/DocPHPManualer.sublime-package

It works again!!!

Really disappointed that the PR is not accepted for so long time.

**Comment by paveljanda** [comment]
@garveen Hi. Could you please merge the referred pull-request? It is really small PR and this package is awesome. :)
Thanks a lot!
