### ISSUE TITLE
Not show in v.3200

### ISSUE THREAD

**Issue by mercurykd** [acabin/docphp#12]
In new version sublime not show.

Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 1088, in run_
    return self.run(edit)
  File "C:\Users\User\AppData\Roaming\Sublime Text 3\Installed Packages\DocPHPManualer.sublime-package\docphp.py", line 331, in run
  File "C:\Users\User\AppData\Roaming\Sublime Text 3\Installed Packages\DocPHPManualer.sublime-package\docphp.py", line 344, in show_popup
  File "C:\Users\User\AppData\Roaming\Sublime Text 3\Installed Packages\DocPHPManualer.sublime-package\docphp.py", line 412, in formatPopup
  File "./python3.3/html/parser.py", line 145, in feed
  File "./python3.3/html/parser.py", line 189, in goahead
  File "./python3.3/html/parser.py", line 372, in parse_starttag
  File "C:\Users\User\AppData\Roaming\Sublime Text 3\Installed Packages\DocPHPManualer.sublime-package\docphp.py", line 528, in handle_startendtag
  File "C:\Users\User\AppData\Roaming\Sublime Text 3\Installed Packages\DocPHPManualer.sublime-package\docphp.py", line 557, in get_tag_text
  File "C:\Users\User\AppData\Roaming\Sublime Text 3\Installed Packages\DocPHPManualer.sublime-package\docphp.py", line 557, in <lambda>
TypeError: can only concatenate tuple (not "str") to tuple

**Comment by mercurykd** [comment]
#13

**Comment by mercurykd** [comment]
My changes broked checkout language(

**Comment by giratek** [comment]
The solution to this problem was found for ST 4. It is necessary in DocPHPManualer.sublime-package archive to change the file docphp.py starting from line 557 correct the function as follows:
`    def get_tag_text(self, tag, attrs, is_startend=False):`
`        t=''`
`        if type(attrs) == dict:`
`            for key in attrs:`
`                t=t+ key + '="' + attrs[key] + '"'`
`        return '<'+ tag + ' ' + t + (' />' if is_startend else '>')`
